name: "🍰 Request a new recipe!"
description: I have a request for a fresh recipe 😋"
title: "[recipe] "
labels: ["recipe/request", "status/backlog", "good first issue"]

body:
  - type: markdown
    attributes:
      value: |
        Greetings, fellow geek! Thanks for taking the time to request this recipe!

  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guide](https://geek-cookbook.funkypenguin.co.nz/community/contribute/) and wholeheartedly agree
          required: true

  - type: input
    id: project_homepage
    attributes:
      label: Project Homepage
      description: Provide a link to the project's homepage
      placeholder: e.g. https://radarr.video/
    validations:
      required: true

  - type: checkboxes
    id: sanity_check
    attributes:
      label: Sanity check
      description: |
        To avoid duplicating work, I have...
      options:
        - label: ...searched and confirmed no existing [open]((https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)) or closed [closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues for this app
          required: true
        - label: ...searched and confirmed no existing [open]((https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr)) or closed [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) issues for this app
          required: true          
        - label: ... confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)
          required: true

  - type: dropdown
    id: authentication
    attributes:
      label: Authentication
      description: |
        Does the app provide its own authentication (_i.e. NextCloud_), or does it require an authentication frontend (_i.e., Radarr_)?

        How should access to the app be managed?
      multiple: false
      options:
        - The app provides its own, trustworthy authentication, or access control is unnecessary. (*I'd be happy exposing it to the internet*)
        - The app needs something in front of it to secure access (_traefik-forward-auth, authelia, etc_)

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://geek-cookbook.funkypenguin.co.nz/community/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true