name: "🍰 Request a new recipe!"
description: I have a request for a fresh recipe 😋"
title: "[recipe] "
labels: ["recipe/request", "status/backlog", "good first issue"]

body:
  - type: markdown
    attributes:
      value: |
        Greetings, fellow geek! Thanks for taking the time to request this recipe!

  - type: checkboxes
    attributes:
      label: Contribution guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guide](https://geek-cookbook.funkypenguin.co.nz/community/contribute/) and wholeheartedly agree
          required: true

  - type: input
    id: project_homepage
    attributes:
      label: Project Homepage
      description: Provide a link to the project's homepage
      placeholder: e.g. https://radarr.video/
    validations:
      required: true

  - type: checkboxes
    id: sanity_check
    attributes:
      label: Sanity check
      description: Let's confirm that this is not a recipe which has previously been discussed / proposed
      options:
        - label: |
            I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue) 
            / [closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues,
            or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this recipe
          required: true       
        - label: I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)
          required: true


  - type: checkboxes
    id: authentication
    attributes:
      label: Authentication
      description: |
        Does the app provide its own authentication (_i.e. NextCloud_), or does it require an authentication frontend (_i.e., Radarr_)?

        How should access to the app be managed? (_pick one if the answer is obvious_)
      options:
        - label: The app provides its own, trustworthy authentication, or access control is unnecessary. (*I'd be happy exposing it to the internet*)    
        - label: The app needs something in front of it to secure access (_traefik-forward-auth, authelia, etc_)

  - type: checkboxes
    id: config
    attributes:
      label: ⚙️ Config Management
      description: How is the app configured? Some applications are configured [entirely using environment variables](https://12factor.net), some need static config files mounted into their container, and some are configured using an interactive setup process (_i.e. NextCloud_). 
      options:
        - label: The app is configured with environment variables
        - label: The app is configured with command-line arguments
        - label: The app is configured with a static config file on the filesystem
        - label: The app is configured interactively which then persists the config to the filesystem

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://geek-cookbook.funkypenguin.co.nz/community/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true