name: "🍰 Request a new recipe!"
description: I have a request for a fresh recipe 😋"
title: "[recipe] "
labels: ["recipe/request", "status/backlog", "good first issue"]

body:
  - type: markdown
    attributes:
      value: |
        Greetings, fellow geek! Thanks for taking the time to request this recipe!

  - type: checkboxes
    id: sanity_check
    attributes:
      label: 🤪 Sanity check
      description: Let's confirm that this is not a recipe which has previously been discussed / proposed
      options:
        - label: I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue) / [closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this recipe
          required: true       
        - label: I have confirmed that the app is actively supported by its developers (_i.e., not deprecated or abandoned_)
          required: true
          

  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the proposed recipe
    validations:
      required: true

  - type: input
    id: project_homepage
    attributes:
      label: 🏠 Project Homepage
      description: Provide a link to the project's homepage
      placeholder: e.g. https://radarr.video/
    validations:
      required: true

  - type: input
    id: discord_id
    attributes:
      label: Your Discord username
      description: If you've joined our [Discord server](http://chat.funkypenguin.co.nz), enter your username here so that we can collaborate effectively
      placeholder: BobTheBuilder#4567

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://geek-cookbook.funkypenguin.co.nz/community/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        That's it for the obligatory checks 👌. You can skip to the bottom and create the issue, or continue below to provide further details.
        
        ---

        The checklists which follow are intended to help to frame the recipe correctly. Provide answers if you have them, else leave them blank. 
        If your're not sure, that's ok, you'll also be able to toggle the checklist items *after* you create the issue.

  - type: checkboxes
    id: authentication
    attributes:
      label: 🔐 Authentication
      description: |
        Does the app provide its own authentication (_i.e. NextCloud_), or does it require an authentication frontend (_i.e., Radarr_)?

        How should access to the app be managed? (_pick one if the answer is obvious_)
      options:
        - label: The app provides its own, trustworthy authentication, or access control is unnecessary. (*I'd be happy exposing it to the internet*)    
        - label: The app needs something in front of it to secure access (_traefik-forward-auth, authelia, etc_)

  - type: checkboxes
    id: config
    attributes:
      label: 💼 Config Management
      description: How is the app configured? Some applications are configured [entirely using environment variables](https://12factor.net), some need static config files mounted into their container, and some are configured using an interactive setup process (_i.e. NextCloud_). 
      options:
        - label: The app is configured with environment variables
        - label: The app is configured with command-line arguments
        - label: The app is configured with a static config file on the filesystem
        - label: The app is configured interactively which then persists the config to the filesystem

  - type: checkboxes
    id: connectivity
    attributes:
      label: 💼 Connnectivity
      description: What sort of network connectivity does the app need?
      options:
        - label: The app requires no network connectivity
        - label: The app requires inbound web access HTTP/S access
        - label: The app requires inbound arbitrary TCP/UDP access
        - label: The app requires connectivity to other apps in its own stack (_i.e., a database_)

  - type: checkboxes
    id: persistence
    attributes:
      label: 💾 Data persistence
      description: What sort of persisted data does the app need?
      options:
        - label: The app needs no persisted data
        - label: The app needs access to its own persistent data (_i.e. logs, database directory, etc_)
        - label: The app needs access to outside data (_i.e. a media player_)

  - type: checkboxes
    id: backup
    attributes:
      label: 🪂 Backup
      description: How is backup of the app's data to be handled?
      options:
        - label: The app does not require backup
        - label: The app can be backed up with a simple filesystem data copy
        - label: The app requires an extra process to create backups for a file-based copy (_i.e., a mysql database dump_)

  - type: dropdown
    id: orchestration
    attributes:
      label: 🤹‍♀️ Orchestration Platform
      description: Which platform(s) are you interested in a recipe supporting?
      multiple: true
      validations:
        required: true
      options:
        - I'm interested deploying the app into Docker Swarm using manual edeiting and classic `docker stack deploy`
        - I'm interested deploying the app into Docker Swarm using [premix](https://geek-cookbook.funkypenguin.co.nz/premix/)'s automated ansible playbooks
        - I'm interested deploying the app into Kubernetes using [premix](https://geek-cookbook.funkypenguin.co.nz/premix/)'s helm charts

  - type: checkboxes
    id: engagement
    attributes:
      label: 💍 Engagement
      description: To get this recipe cooked, I'm willing to...
      options:
        - label: I plan to test the recipe after publication and provide feedback
        - label: I plan to submit a PR for this recipe
        - label: I'm happy to provide community support in Discord re the recipe

